In [92]:
#IMPORTANDO LIBRERÍA NUMPY

import numpy as np

In [93]:
#Creando una lista de 10 Elementos

lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Transformando la Lista a un Array   

In [94]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
#Corroborando el tipo de estructura

type(arreglo)

numpy.ndarray

In [96]:
#Corroborando el tipo de datos del arreglo
arreglo.dtype

dtype('int32')

In [97]:
#Definiendo el Array de int32 a float32

np.array(arreglo, dtype=np.float32)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [98]:
#Sigue siendo un array de int32

arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
#Transformando los datos de int32 a float32

arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [100]:
#También existe una función similar a Range pero ocupando Arrays

arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:

#Arreglo de 2 en 2 utilizando Arange

arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

ALGUNAS FUNCIONES DE NUMPY




In [102]:
#Obteniendo el promedio del array

promedio = np.mean(arreglo)
promedio



5.5

In [103]:
#Obteniendo la mediana del array

mediana = np.median(arreglo)
mediana


5.5

In [104]:
#Desviación Estandar del Arreglo

desviacion_std = np.std(arreglo)
desviacion_std


2.8722813232690143

In [105]:
#Generación de un arreglo de 10 elementos de solo unos

arreglo_de_unos = np.ones(10)
arreglo_de_unos 


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
#Generación de un arreglo de 10 elementos de solo ceros

arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

In [107]:
#Transformando el arreglo de unos de punto flotante a enteros

arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

UTILIZANDO LA FUNCIÓN RANDOM

In [108]:
#Generando arreglo aleatorio de 5 elementos

arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 


array([0.6193055 , 0.37657127, 0.61130467, 0.19796501, 0.00899376,
       0.97626087, 0.62491369, 0.58878518, 0.56247772, 0.85292819])

In [109]:
#Generando una matriz aleatoria de 3x3

matriz = np.random.rand(3,3)
matriz

array([[0.73849972, 0.30887929, 0.93465386],
       [0.33271925, 0.07145634, 0.09733602],
       [0.41685917, 0.60140705, 0.4658178 ]])

In [110]:
#Generando un arreglo aleatorio de 10 números enteros del 1 al 5

arreglo_aleatorio2  = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([821, 648, 714, 449, 497])

In [111]:
#Generando una matriz aleatoria de 10 números enteros del 1 al 100

matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[16, 26, 84, 10, 73,  1, 10, 74, 35, 48],
       [76, 30, 14, 92, 60,  9,  7, 51, 33, 17],
       [25, 69, 73, 81, 53, 81, 85, 94, 35, 72],
       [37, 78, 71, 62,  6,  4, 86, 30, 23, 72],
       [36, 48, 28, 41,  1, 53, 47, 35, 49, 47],
       [10, 29, 85, 17,  6, 69, 24, 72, 97,  4],
       [93, 88, 69, 78, 87, 18, 13, 25, 26, 82],
       [35, 11, 58, 13,  9, 25, 22, 51, 50, 82],
       [25, 81, 86, 43, 69,  8, 65, 92, 25, 69],
       [96, 56, 59,  5, 39, 92, 63,  2, 69, 96]])

In [112]:
matriz3= np.ones((5,5))
matriz3[1:-1,1:-1]=3
matriz3


array([[1., 1., 1., 1., 1.],
       [1., 3., 3., 3., 1.],
       [1., 3., 3., 3., 1.],
       [1., 3., 3., 3., 1.],
       [1., 1., 1., 1., 1.]])