In [4]:
import numpy as np

Generando un Array de 12 elementos enteros con Random

In [15]:
arreglo = np.random.randint(1,10,12)
arreglo

array([4, 6, 9, 6, 8, 2, 3, 7, 7, 6, 7, 1])

Obtener la dimensión de un arreglo

In [16]:
np.shape(arreglo)

(12,)

Transformación del vector de 12 elementos a Matriz 4x3 con Reshape

In [19]:
matriz = arreglo.reshape(3,4)
matriz

array([[4, 6, 9, 6],
       [8, 2, 3, 7],
       [7, 6, 7, 1]])

In [18]:
np.shape(matriz)

(3, 4)

Transformación del vector de 12 elementos a Matriz 4x3 con Reshape

Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape

In [9]:
matriz = arreglo.reshape(3,4)
matriz

array([[7, 6, 3, 2],
       [1, 4, 1, 5],
       [8, 4, 8, 5]])

Creando un Tensor

In [10]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]